#ansible-playbook -i inventory app_install.yaml

---

- hosts: all
  become: yes
  tasks:
    - name: Install applications
      yum:
        name: "{{ item }}"
        state: present
      # with_items:
      #   - vim
      #   - sqlite
      #   - jq
      with_items:
        - "{{ app_list }}"
